### ISSUE TITLE
Problem with Restyler Job #330368

### ISSUE THREAD

**Issue by sambacha** [restyled-io/restyler#110]
Please use the below template to report an issue with this Job. **Don't submit
sensitive information**, this is a public project. If you'd rather communicate
privately, email support@restyled.io.

---

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/freight-trust/repos/protocol/jobs/330368
- **GitHub PR**: freight-trust/protocol#11

**What I expected to happen**:
To format the files according to spec, ignore malfored files 

**What happened instead**:
job incomplete, quit upon interacting with malformed files 

```
stderrWARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
stderrparse error: Unfinished JSON term at EOF at line 17, column 2
stdoutSetting status of error for 6daf4af
```
**Configuration** (if applicable):
default 

```yaml
# .restyled.yaml as it was in the commit for the Job
```

I am unsure if it was because of the file or because of the error message posted above.

**Comment by pbrisbin** [comment]
Thanks for the report!

> To format the files according to spec, **ignore malfored files** [sic]

This seems like the core issue here. You've got some JSON files that are not valid JSON, so `jq` errors on them, while you'd prefer they be silently skipped. Do you agree with that characterization?

I'm not against it as a feature; probably an argument to the `jq` Restyler:

```yaml
restylers:
  - jq:
      arguments: ["--ignore-errors"]
```

Note that this would most likely have to ignore _any_ `jq` errors, not specifically those caused by malformed JSON -- though I don't know what other kind of errors would be possible.

---

For now, as a workaround, you could configure Restyled entirely (via `exclude`), or `jq` specifically (via `restylers[jq].include`), to not process these files. How convenient that is depends on where they live -- for example if they all happen to be under a single directory, it would be very easy.

- https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled#exclude
- https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled#restyler-override

**Comment by sambacha** [comment]
Thank you, working great, really liking restyler, quick question: would it be possible to have restyler fix hash digests so that they are properly checksummed? 

Thanks again

**Comment by pbrisbin** [comment]
Any process that can rewrite a file and change something in it contents can be made into a Restyler. The only limitations are that it can't make an outgoing network call and must live within our general memory and time constraints.

The example documentation uses a simple word-swapping script: https://github.com/restyled-io/restyled.io/wiki/Adding-a-Restyler#0-the-auto-formatter.

I actually have no idea what you mean by "fix hash digests so that they are properly checksummed", can you say more?
