### ISSUE TITLE
Restyler Bot opens PR with wrong target branch

### ISSUE THREAD

**Issue by DanielHabenicht** [restyled-io/restyler#126]
Hi again, 

Reviewing a PR I just came across an odd behaviour of your restyler bot (hope this is the right repository). 

This PR https://github.com/CovOpen/CovMapper/pull/77 wants to merge into master instead of into the Pull Request. 
It comes from a fork,  maybe that's the issue?

**Comment by pbrisbin** [comment]
This comes up quite a bit, I need to write a dedicate wiki page for it.

There's discussion happening in https://github.com/restyled-io/restyled.io/issues/201, but...

When Restyled runs on a Fork, it doesn't have permissions to make a PR-from-PR like it usually does, since the original PR is in the _contributor's_ repository, not in the user who's installed Restyled.

So what we do is open a new PR against the default branch that includes the contributed commit(s) and then any style fixes on top. The Pull Request description tries to clarify:

![](https://files.pbrisbin.com/screenshots/screenshot.563827.png)

**Comment by DanielHabenicht** [comment]
Ahh ok, can you maybe add a Warning sign?⚠️ 
With people not familiar with restyled that might lead to unintentionally merged Pull Request into the main line. 

I almost didn't read what was written there, because it in my flow to just merge :)

**Comment by pbrisbin** [comment]
I like the warning sign, will do.
