### ISSUE TITLE
Problem with Restyler Job #1277580

### ISSUE THREAD

**Issue by KochankovID** [restyled-io/restyler#173]
Please use the below template to report an issue with this Job. **Don't submit
sensitive information**, this is a public project. If you'd rather communicate
privately, email support@restyled.io.

---

Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/TNLinc/repos/TonalCreamAssistant/jobs/1277580
- **GitHub PR**: TNLinc/TonalCreamAssistant#57

**What I expected to happen**:
Successful build

**What happened instead**:
Error with yapf

**Configuration** (if applicable):

```yaml
# .restyled.yaml as it was in the commit for the Job
```
same as
https://github.com/restyled-io/restyler/issues/163

**Comment by pbrisbin** [comment]
Oh, sorry about this. It was "fixed" in response to the first issue in https://github.com/restyled-io/restylers/pull/254, but since the version of `yapf` didn't change, a new image wasn't built or released. I've just addressed that by adding a release suffix to trigger a new image:

```console
% docker run --rm restyled/restyler-yapf:v0.31.0-1 pip show toml
Name: toml
Version: 0.10.2
Summary: Python Library for Tom's Obvious, Minimal Language
Home-page: https://github.com/uiri/toml
Author: William Pearson
Author-email: uiri@xqz.ca
License: MIT
Location: /usr/local/lib/python3.10/site-packages
Requires:
Required-by:
```

This should be available in `dev` in a few hours and `stable` in a week at most.
