### ISSUE TITLE
Problem with Restyler Job #1632927

### ISSUE THREAD

**Issue by xylophone21** [restyled-io/restyler#176]
Please use the below template to report an issue with this Job. **Don't submit
sensitive information**, this is a public project. If you'd rather communicate
privately, email support@restyled.io.

---

Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/project-chip/repos/connectedhomeip/jobs/1632927
- **GitHub PR**: project-chip/connectedhomeip#16475

**What I expected to happen**:

**What happened instead**:

**Configuration** (if applicable):

```yaml
# .restyled.yaml as it was in the commit for the Job
```

**Comment by pbrisbin** [comment]
Hi there, this looks like [this common error](https://github.com/restyled-io/restyled.io/wiki/Common-Errors:-Push-Rejected#but-theres-no-change-to-a-workflow-file-at-all).

It can be confusing because your PR clearly doesn't change a workflow file, but I see:

> This branch is 9 commits ahead, 28 commits behind project-chip/connectedhomeip:master. 

What we've seen is that if a change to a workflow file exists in those 28 commits you are behind, GitHub will (incorrectly, IMO) flag it as not allowed for bots to push.

If so, the fix would be to rebase your branch.
