### ISSUE TITLE
Problem with Restyler Job #2906596

### ISSUE THREAD

**Issue by jrhees-cae** [restyled-io/restyler#201]
Please use the below template to report an issue with this Job. **Don't submit
sensitive information**, this is a public project. If you'd rather communicate
privately, email support@restyled.io.

---

Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/project-chip/repos/connectedhomeip/jobs/2906596
- **GitHub PR**: project-chip/connectedhomeip#25436

**What I expected to happen**:
Be able to download patch or logs

**What happened instead**:
Cannot download patch or logs. Server times out or does not respond

**Comment by pbrisbin** [comment]
[Copying my reply to the separate email you sent about this, I'll now keep discussion here]

Thanks for the report, I see a few things to fix:

- That should render as a (slightly) more informative page. An un-handled "<<timeout>>" exception generating a 500 should really be handled to a 503 and "I'm sorry that's taking too long" page.
- It seems like our `/patch` route is still under the default 2s timeout, even though it should really be opted out of it just like we do the `/log` route (it's actually the same data, the patch is emitted as part of the build log). These responses just take a while to shuttle from our log data store.

I'll try to get these things corrected this next week.

**Comment by pbrisbin** [comment]
I think this is fixed by https://github.com/restyled-io/restyled.io/commit/c935d4f3b359e76f47fbb8fffd0dcc575f843eba. I'm at the "how did this ever work" stage of things though. This code (the broken `AWSPager` instance) has existed like this since we first implemented the feature. I don't know how `/patch` has ever worked for anyone.

🤷 Either way, I will close the issue once I verify the fix in production. Thanks for the report.
