### ISSUE TITLE
Problem with Restyler Job #4140417

### ISSUE THREAD

**Issue by nurupo** [restyled-io/restyler#231]
Please use the below template to report an issue with this Job. **Don't submit
sensitive information**, this is a public project. If you'd rather communicate
privately, email support@restyled.io.

Before reporting, please check the _Common Errors_ section found in [the wiki](https://github.com/restyled-io/restyled.io/wiki)
sidebar.

---

Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/TokTok/repos/c-toxcore/jobs/4140417
- **GitHub PR**: TokTok/c-toxcore#2713

**What I expected to happen**:

It doesn't attempt to restyle workflows because I added appropriate excludes in the PR https://github.com/TokTok/c-toxcore/pull/2713/commits/0a1efc026125401d4e5dd5a6951eb479aea2baf0

**What happened instead**:

It still attempts to restyle workflows.

**Comment by nurupo** [comment]
Yep, that indeed was the case. iphy opened a PR with all my changes except the ones done on the workflow files, Restyled restyled them https://github.com/TokTok/c-toxcore/pull/2716, I applied the patch to my PR and Restyled is happy now.

It's rather annoying that if I modify any workflow file and my some non-workflow files in the PR need to be restyled -- Restyled is unable to tell me what changes need to be made as it can't open a new PR, can't push into the existing PR and the "Download patch" option on the Restyled web page also doesn't work.

Btw, here is what Restyled did when I tried to make it push to my PR (it's not clear what `auto` being true or false is supposed to do, so I tried both):

- `auto: true`
   - https://github.com/TokTok/c-toxcore/commit/e3ba7021bb64fd5137f4bd586d0ab27efcac19e2
   - https://restyled.io/gh/TokTok/repos/c-toxcore/jobs/4140457
- `auto: false`
   - https://github.com/TokTok/c-toxcore/commit/2662f82099689ceef37fa649720ee49422d971d1
   - https://restyled.io/gh/TokTok/repos/c-toxcore/jobs/4140460
   
In the both cases it was trying to push into its own separate PR. Is that right? I thought one of those was supposed to make it push into my PR. Or perhaps there is some bug in Restyled where it remembers that it already has opened its own PR for restyling this PR before, and gets locked into pushing into its own PR no matter what the `auto` option says?

**Comment by pbrisbin** [comment]
Thank you very much for all the details!

Just to clarify the expected behavior, when Restyled operates on PRs from forks (`TokTok:master <- iphydf:restyle-pr`), it's not supposed to do any of this. We cannot push to the PR (`auto:true`) because we do not have write permissions to `iphydf` as we are an App installed on, and using a token for, `TokTok`. We **used to** create theses PRs that housed the original change plus the style fixes instead, but we not longer do that out of security concerns ([more details](https://github.com/restyled-io/restyled.io/wiki/2022.08.03-Attack-on-Forked-PRs#when-will-restyled-run-successfully-on-fork-prs-again)). Instead, we simply create a patch and provide a link and instructions in the log for you to apply the patch locally and push. I don't know why that's not happening in this case, and seemingly old/removed behavior is happening instead. It's as if your repository is running an older version of the CLI unexpectedly.

I will have to investigate further.

**Comment by pbrisbin** [comment]
Huh, well I can explain part of it, it seems you have 13 repositories that are configured to use a specific version of our `restyler_image`, rather than "latest":

```
restyled-io::DATABASE=> select owner, name, restyler_image from repo where restyler_image is not null;
 owner  |     name     |        restyler_image
--------+--------------+------------------------------
 TokTok | toxins       | restyled/restyler:670ad1cb5f
 TokTok | dockerfiles  | restyled/restyler:670ad1cb5f
 TokTok | jtox         | restyled/restyler:670ad1cb5f
 TokTok | py-toxcore-c | restyled/restyler:670ad1cb5f
 TokTok | hs-cimple    | restyled/restyler:670ad1cb5f
 TokTok | echobot-jvm  | restyled/restyler:670ad1cb5f
 TokTok | .github      | restyled/restyler:670ad1cb5f
 TokTok | experimental | restyled/restyler:670ad1cb5f
 TokTok | qTox         | restyled/restyler:670ad1cb5f
 TokTok | toktok-stack | restyled/restyler:670ad1cb5f
 TokTok | js-toxcore-c | restyled/restyler:670ad1cb5f
 TokTok | c-toxcore    | restyled/restyler:670ad1cb5f
 TokTok | toxic        | restyled/restyler:670ad1cb5f
(13 rows)
```

I have no memory of setting that, and I apologize if it was some operational mistake on my part. But I will clear it, which should cause your repositories to use the latest version, which has the behavior I described.

This is good and bad, since Restyled will no longer create _any_ Restyled PRs for PRs from forks. Instead, it will present a patch and `git` instructions for your contributors to execute and push themselves. Unfortunately, that's the only secure way to deal with restyling external contributions.

Let me know if you have any additional questions!

**Comment by pbrisbin** [comment]
My fix seems to have worked. Here's an example: https://restyled.io/gh/TokTok/repos/c-toxcore/jobs/4141959

Restyled correctly did not open any sibling PR and instead presented the patch instructions.

**Comment by nurupo** [comment]
@pbrisbin thanks for fixing this, the linked attack vector does sound nasty. I have used restyled only in TokTok so far, so had no idea it was somehow outdated. iphy did mention that in other projects the bot just provides a patch in the output, but I thought he meant that the bot just submits a patch to the PR and worded it weirdly, as `auto`, `pull_requests`, etc. aren't marked as deprecated [on the Configuration page of the wiki](https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled), and there is no configuration option for providing patches on the restyled website so it seemed like something that impossible to enable thus non-existent, but now I understand what he meant.

Just curious, is it possible for users to specify a version of `restyler_image` they want to use, or is that impossible and that was some sort of a bug on the backend? Because if it's possible to specify `restyler_image`, an attacker could open a bad-style PR with with `restyled.yaml` instructing to use an older `restyler_image` version that allows for that attack vector, bypassing the mitigation.

Anyway, thank you for providing restyled, to has been very useful in TokTok! Also surprised to receive such a prompt response on the issue, you rock! :)

**Comment by iphydf** [comment]
Thanks @pbrisbin. I do remember you setting a specific version at some point because I was testing not-yet-released code. I guess we never unset that. I had been wondering why some repos still do the "send PR" thing, while others give a patch to be applied by curl+git am (I actually use `patch -R`). I prefer the new way, because opening restyled PRs consumes a lot of PR numbers and artificially inflates PR count. It also spams people's inboxes. Thanks again for correcting that.

**Comment by pbrisbin** [comment]
@nurupo 

> as auto, pull_requests, etc. aren't marked as deprecated [on the Configuration page of the wiki](https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled), and there is no configuration option for providing patches on the restyled website so it seemed like something that impossible to enable thus non-existent

Yeah, I can see how that might be confusing. The thing is the patch is _always_ provided (now). It's just present and part of the build logs every time. And the `auto` and `pull_request` options are perfectly valid -- for non-fork PRs. It's just this special behavior for forks that should probably be better documented there.

> Just curious, is it possible for users to specify a version of restyler_image they want to use, or is that impossible and that was some sort of a bug on the backend? Because if it's possible to specify restyler_image, an attacker could open a bad-style PR with with restyled.yaml instructing restyled to use an older restyler_image version that allows for that attack vector, bypassing the mitigation.

Yeah, that's a good insight. It is indeed not possible to pick the `restyler_image` from your configuration. The configuration is read by the CLI, so by the time you get there you are already in your chosen image -- which is decided by the backend. I did plan to make it user configurable, but it would be through an admin UI on the website, not via configuration -- for exactly the reason you noticed.

> Anyway, thank you for providing restyled, it has been very useful in TokTok! Also surprised to receive such a prompt response on the issue, you rock! :)

Thanks!

> I prefer the new way, because opening restyled PRs consumes a lot of PR numbers and artificially inflates PR count. It also spams people's inboxes

Makes sense. FWIW, you can disable this behavior for non-Forks too with `pull_requests: false` in configuration.

**Comment by iphydf** [comment]
Thanks, we don't do non fork pull requests, but it's good to know.
