### ISSUE TITLE
Problem with Restyler Job #3955534

### ISSUE THREAD

**Issue by jmorlock02** [restyled-io/restyler#234]
Please use the below template to report an issue with this Job. **Don't submit
sensitive information**, this is a public project. If you'd rather communicate
privately, email support@restyled.io.

Before reporting, please check the _Common Errors_ section found in [the wiki](https://github.com/restyled-io/restyled.io/wiki)
sidebar.

---

Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/whoisdsmith/repos/BOOKMRKS-MTHRFCKR/jobs/3955534
- **GitHub PR**: whoisdsmith/BOOKMRKS-MTHRFCKR#5

**What I expected to happen**:

**What happened instead**:

_Please try to be specific. Avoid saying "it failed" or "it errored"; instead,
copy over any error messages or other details when available._

**Configuration** (if applicable):

```yaml
# .restyled.yaml as it was in the commit for the Job
```

**Comment by pbrisbin** [comment]
Hi there- sorry you're having trouble with this Job. I'm closing this Issue (for now) because you've not filled out the template with any details about what's gone wrong. Without more context on your specific case, I'm afraid we won't be able help. If you get a chance to add those details to the Issue and re-open, that'd be great!
