### ISSUE TITLE
Problem with Restyler Job #4651560

### ISSUE THREAD

**Issue by dswan36** [restyled-io/restyler#265]
Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/dswan36/repos/ghstats/jobs/4651560
- **GitHub PR**: dswan36/ghstats#11
```bash
info     Restyler started                                   owner="dswan36" pull=11 repo="ghstats"
info     Cloning repository                                
info     Fetching remote file                               path="/tmp/restylers-stable.yaml"
error    Exception:
Error loading restylers.yaml definition:
InvalidYaml (Just (YamlParseException {yamlProblem = "control characters are not allowed", yamlContext = "", yamlProblemMark = YamlMark {yamlIndex = 0, yamlLine = 0, yamlColumn = 0}}))

===

- https://github.com/restyled-io/restyled.io/wiki/Restyler-Versions
- https://github.com/restyled-io/restyled.io/wiki/Common-Errors:-.restyled.yaml
 error={description:"bad Restylers manifest",exitCode:12,severity:"error",tag:"invalid-restylers-yaml"}
info     Restyler done 
```

**What I expected to happen**:
Restyle job to complete successfully

**What happened instead**:
Restyle job threw YAML error with the default configuration (due to no other configuration specified) 

**Configuration** (if applicable):
Default configuration (as no restyled.yaml exists in the repo)

No clue why this happened, if I get more info I will update this

**Comment by pbrisbin** [comment]
That is very odd! Thank you for reporting.

I'm inclined to think this was some kind of temporary networking hiccup. I've verified the [restylers manifest](https://docs.restyled.io/data-files/restylers/manifests/stable/restylers.yaml) that this Job claims was invalid looks correct, and it's not been updated since 7/15, and [other jobs](https://restyled.io/gh/dswan36/repos/ghstats/jobs/4651561) have successfully pulled and parsed it since. I've also seen no uptick in our general error rate and, if there were bad data in that file, every single one of our users would be failing in this way.

**Comment by dswan36** [comment]
I also found it very odd because I assumed the only way for this to typically happen, would be if the master restyler file got borked. Which would warrant more than just my report. But it would be interesting to monitor, and if a cause could be determined that might be informative.
