### ISSUE TITLE
What if restyled.io restyled the whole code base on an interval?

### ISSUE THREAD

**Issue by maxjacobson** [restyled-io/restyler#56]
Hi Pat!

I was thinking about Restyled, which I think is super cool although admittedly I haven't had a chance to try using it yet. I wanted to share this idea to see what you think.

My team has adopted using prettier for our JavaScript/TypeScript/SCSS, and it's been a game changer. We have some docs in our README explaining things like how to configure a git hook to auto-run it, or how to configure your editor to auto-run it. When we first added it, we did a "big bang reformat" on the whole code base, and then going forward we ABR (always be reformatting; I just made this up). For the most part, this works great. Thru a variety of snafus, a few non-prettier-compliant formatting changes have made it thru to our default branch. This isn't hurting anyone, and if anyone touches those files again, they'll get reformatted at that time.

But anyway, it made me think: what if we had a bot that ran prettier once a week, maybe at the end of the week, and cleaned up any formatting mistakes that snuck thru to master?

In that world, there's at most one restyled PR per week. I feel like having a lot of restyled PRs has the potential to feel noisy, although that's just speculation on my part.

Here's what I see as the pros and cons:

Pros:

1. Contributors can just contribute, and their PRs can remain focused on whatever logic/design/whatever they're focused on (less noise)
2. If a formatting booboo makes it to the default branch, that will get cleaned up (eventual consistency 😉)

Cons:

1. With the current restyled workflow, assuming people squash-and-merge or squash before merging, the git-blame on the default branch should generally not point to the bot, but with this workflow, it would
1. You will encounter incorrectly-formatted code more often throughout the week while working on branches freshly checked out from the default branch

Max

**Comment by pbrisbin** [comment]
Hey Max, thanks for suggesting this! I have a number of ideas :)

## 1- I think this is a totally complimentary approach

Restyled doesn't intend to force *only* using it, or *only* using the PR-from-PR workflow. I fully expect your team to have editor integrations set up to run prettier during normal local development, then Restyled just catches and (conveniently) addresses PRs that snuck by the editor tooling (or were opened by a cross-functional team member that hasn't invested in a local workflow).

This is why I'm careful to run reformatters in a non-opinionated way and ensure they always respect their own in-repo configuration files (e.g. `.prettier.json`). It also motivated Restyled configuration points to support a "status-only" style of usage.

I'd love to know why you all are using prettier but not Restyled, and you know, convince you to change that :)

From there, *additionally* having a once-a-week reformatting of all of master in a dedicated PR to catch whatever slips through the PR cracks makes sense. I would probably have this as an opt-in, paid feature that you enable by repo on your Profile page. There's also the option of configuring it in `.restyled.yaml`, but that gets strange with when/how we find that setting for a non-user-initiated action such as a weekly reformat.

## 2- This is possible to do yourself today

I'm not suggesting we stop here, but just wanted to let you know you could do this "manually" using [restyle-path](https://github.com/restyled-io/restyler/blob/736a37bc4dd53da4e1284c89a1a695dd8338a2cf/bin/restyle-path#L1) if you wanted to.

You would basically maintain your own branch and PR where you:

```console
git fetch origin
git reset --hard origin/master
restyle-path **/*
git commit -am 'Restyle the world'
git push --force-with-lease
```

On whatever cadence you prefer.

## 3- About your Pros and Cons

> Pros:
> 
> 1. Contributors can just contribute, and their PRs can remain focused on whatever logic/design/whatever they're focused on (less noise)

By saying "Contributors" I think you're referring to outside contributors via forks. I just want to mention that you can achieve a "less noise" experience for them today by:

- Disabling comments and/or PR statuses

  Then, the contributor won't know about anything Restyled may or may not have done. Today, these settings apply to `origin` or `forked` PRs, but I could easily make it possible to separately configure that.

- Configuring review-requests

  This setting *is* separately configurable already, and the default behavior (once enabled) for a `forked` PR is to request review from the repository owner (not PR author like for `origin` PRs). This approach would allow Restyled to still ping *them* to clean up style before accepting the contribution, but doesn't bug the contributor themselves.

> 2. If a formatting booboo makes it to the default branch, that will get cleaned up (eventual consistency wink)

:+1:

> Cons:
>
> 1. With the current restyled workflow, assuming people squash-and-merge or squash before merging, the git-blame on the default branch should generally not point to the bot, but with this workflow, it would

I think, if we push the "complimentary" approach, the things that sneak into master will be really rare as they'd have to get past local workflow *and* Restyled PRs. Even without this additional rarity, we've decided on my own team that the consistent formatting is worth muddying history with bot commits as necessary. That said, we try to do them as big-bang as possible to establish "epochs" in the history that you can more easily move across to find real history, rather than little landmines here and there. So maybe being more manual about is better for our own needs :man_shrugging: .

> 2. You will encounter incorrectly-formatted code more often throughout the week while working on branches freshly checked out from the default branch

Again, I think I'd push for complimentary with a normal PR-from-PR Restyled flow. Then you don't have this Con.

---

WDYT?

**Comment by eborden** [comment]
> Thru a variety of snafus, a few non-prettier-compliant formatting changes have made it thru to our default branch. 

IMHO This is exactly what restyled guards you against, in a non-obtrusive way. The other method to accomplish this is a blocking `format` and `diff` step in CI, but that is far more obtrusive and requires investment and maintenance to do it in a way that scales. Why bother when restyled exists?

**Comment by eborden** [comment]
Another con to add to the pile:

Re-formatting an entire codebase can be trivial, but as companies grow so can their codebases. Re-formatting an entire codebase can become a very large task. Having to run these large jobs on a regular basis is a lot of compute time for what will mostly produce `noop` changes. By allowing restyled to track changes as they are made it can intelligently format smaller chunks of code and operate quicker and cheaper than full codebase re-formattings.

**Comment by pbrisbin** [comment]
Thanks for the discussion here. I'm going to close this as it's seemed to die down and I'm not sensing any strong desires to do anything in this space.
