### ISSUE TITLE
Problem with Restyler Job #223557

### ISSUE THREAD

**Issue by chintan9** [restyled-io/restyler#82]
Please use the below template to report an issue with this Job. **Don't submit
sensitive information**, this is a public project. If you'd rather communicate
privately, email support@restyled.io.

---

Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/chintan9/repos/plyr-react/jobs/223557
- **GitHub PR**: chintan9/plyr-react#169

**What I expected to happen**:

**What happened instead**:

**Configuration** (if applicable):

```yaml
# .restyled.yaml as it was in the commit for the Job
```

**Comment by pbrisbin** [comment]
Hi there- sorry you're having trouble with this Job. I'm closing this Issue (for now) because you've not filled out the template with any details about what's gone wrong. I can see the Job errored and could take some guesses as to why, but without more context on your specific case, I'm afraid we won't be able help. If you get a chance to add those details to the Issue and re-open, that'd be great!
