### ISSUE TITLE
Add option to restyle all files 

### ISSUE THREAD

**Issue by DanielHabenicht** [restyled-io/restyler#84]
It would be great if restyled could open a Config PR with the default config and all restyle changes so that all files are formatted according to restyle. 

It would only open as long as no config is in the repo.

**Comment by pbrisbin** [comment]
For context, there was a long discussion about the "re-format all files" feature in #56. Ultimately, we decided it was not worth it. However, there weren't many voices in that conversation, so I welcome your input too.

What event do you think would trigger this Config PR? Immediately on installation?

**Comment by DanielHabenicht** [comment]
Well, I think I will split up what I want to achieve otherwise it would get to messy. 

1. Want I want to achieve what #56 described as a Big Bang Format: Restyle every file that would otherwise get restyled as the files are touched. (just as cli option for now, like a run once command)

2. A Config PR allowing easy configuration of restyler, just like Renovate does with its Onboarding PR (https://docs.renovatebot.com/configure-renovate/) 

3. Combine both, thus making the config options visible by "previewing" the changes and then merging the config and all restyled files.

**Comment by pbrisbin** [comment]
Gotcha, thanks for clarifying!

Do you think the `restyle-path` executable is a reasonable way to achieve (1)? I understand it may not be discoverable, or the best ergonomics, but I think we could solve those problems -- unless you think there's a fundamental reason that running something locally to get yourself that "Big Bang" PR is a non-starter.

I love the idea of some on-boarding interaction, as an opportunity to familiarize the user with how things work. I do think there's a real problem in terms of discover-ability of what Restyled offers, since most feedback conversations I have do mention "missing" or "broken" things that Restyled actually does have and handle correctly.

My concerns for this concrete version of that are:

1. Having this on-boarding PR commit a config means the our on-boarding process would necessarily fix the user's configuration to that point in time. Lots of my configuration choices rely on the fact that un-specified values will move along with development as I improve or upgrade things (e.g. Restyler versions), so having all users on-boarded to a static config as of that point in time can create a "legacy users" problem down the line

2. Making the "Big Bang" restyle and opening it as PR will be "a lot" on many axis. It would be a lot of computational resources for Restyled (which is real, limited dollars for me at this stage of the project) and it would (IMO) frequently open massive PRs that GitHub just truncates in diff view anyway

3. I'm hesitant to lose the "Just Install and go" nature of the current App. An on-boarding PR that includes a massive diff of a big-bang restyle is going to be high effort to merge (IMO) because now you have to actually think about how this thing is changing thousands of lines of your code. I'm not sure I want to put such a blocker in the path of on-boarding and getting the real "keep on top of each PR" value we offer

As a concrete alternative that attempts to address these concerns, what do you think of this:

1. Assume Restyled doesn't run unless there's a `.restyled.yaml` present
1. On Installation, open an on-boarding PR (solves your 2)
1. Build some intelligence that writes out a config appropriate for the project (e.g. check what file-types are present, if any auto-formatter configs exist, etc), **don't** write an exhaustive configuration that is meant to document all possibilities (solves my 1)
1. In the description, make it clear that the user can:

   - Just merge this PR to get going (semi-solves my 3)
   - Leave a comment (or some other action) to turn this into a "Big Bang" PR (solves your 1 and 3)

WDYT?

**Comment by DanielHabenicht** [comment]
I like your solution. 

> Do you think the restyle-path executable is a reasonable way to achieve (1)? I understand it may not be discoverable, or the best ergonomics, but I think we could solve those problems -- unless you think there's a fundamental reason that running something locally to get yourself that "Big Bang" PR is a non-starter.

Sounds good for me. Maybe just a docker container with the tool installed. Then you can simply run it on your mounted folder...

I also like you alternatives. I wouldn`t go as far as:
>Build some intelligence that writes out a config appropriate for the project (e.g. check what file-types are present, if any auto-formatter configs exist, etc), don't write an exhaustive configuration that is meant to document all possibilities (solves my 1)

just committing a `.restyled.yml` with 
```yml
enabled: true
```
would be enough for me. That way it doesn't interfere with "configuration fix to a specific time". 

The PR can then show everything you named and give more insight into what the current (default) config is doing and how to change it. Also how to make the first "Big Bang" restyle (maybe also automate the creation of this PR). 

Regarding:
> Making the "Big Bang" restyle and opening it as PR will be "a lot" on many axis. It would be a lot of computational resources for Restyled (which is real, limited dollars for me at this stage of the project) and it would (IMO) frequently open massive PRs that GitHub just truncates in diff view anyway

Maybe it would be an option to transfer restyler to a  ´github-action` as well, thus relieving you from running the server and leaving it to GitHub. (e.g. https://github.com/pascalgn/automerge-action is doing the same)

**Comment by DanielHabenicht** [comment]
Running `docker run --rm -it --env DEBUG=1 --env UNRESTRICTED=1 --volume $pwd:/code" --entrypoint "restyle-path" "restyled/restyler" "./"` ignores the path `"./"` and prints: 
```bash
[debug] Paths: []
```
Any idea why?

**Comment by pbrisbin** [comment]
Oh there's a few tricks to doing this... Look for the restyle-path script
in the repo, it should handle everything for you. Sorry for lack of links,
on mobile.

**Comment by DanielHabenicht** [comment]
No worries, this can wait till another day. 

I am not very familiar with Haskell. But if you explain I can write some docu afterward.

**Comment by pbrisbin** [comment]
On second thought, it looks like you were using (the command from)
restyle-path... It just doesn't know how to expand directories right now.
You have to pre-expand on the shell first via glob or find-exec. I'm happy
to change it though so that usage works.

**Comment by pbrisbin** [comment]
I created some separate Issues out of this. I'm going to close this one so we can pick up any discussion there.

I'm going to continue mulling over how Restyled and GitHub Actions interact, but I'm not ready to formalize my thoughts into an Issue just yet.
