### ISSUE TITLE
If directory contains circular symlinks restyler-path infinitely spins

### ISSUE THREAD

**Issue by terafin** [restyled-io/restyler#94]
We have a repository that unfortunately on a development tree (vs a normal checkout) create symlinks back up the tree. This seems to break restyler-path.

I have tried using excludes, but can't make this work... here's a snippet of my excludes path:

```
    - "third_party/**/*"
    - "third_party/**"
    - "third_party/*"
    - "**/third_party/**/*"
    - "**/third_party/*"
    - "**/third_party/**"
    - "**/third_party/**/*"
    - "examples/XXXXX/XXXXX/third_party/**/*"
    - "examples/XXXXX/XXXXX/third_party/*"
    - "examples/XXXXX/XXXXX/third_party/**"
```

Note: All the circuitous links are in a subdirectory named `third_party` ... Maybe my syntax is wrong? As you can see I'm trying multiple versions of it.

**Comment by terafin** [comment]
To be more specific, the bottom ignore shows the structure problem

`examples/XXXXX/XXXXX/third_party/some_link` => links to => the root project directory in some cases

**Comment by pbrisbin** [comment]
> Maybe my syntax is wrong?

No, unfortunately, the "expand any directory arguments into files" logic just runs first, before passing the resolved list of files onto the actual restyling process, which is where excludes would be applied. So that logic is spinning before anything even attempts to look at excludes. I don't think I would change that state of affairs, since it would mean conflating two very separate responsibilities IMO, argument processing and actual restyling.

This is definitely a bug though, and should be a [very localized](https://github.com/restyled-io/restyler/blob/831c8014475745bd672a4a9857fd910adbf17000/restyle-path/main.hs#L88-L96) fix, but I'm just not sure the best approach. Maybe it should ignore symlinks altogether? That would be very simple, but I'm just not sure if it would break other expectations.

**Comment by pbrisbin** [comment]
As a workaround, I would recommend using `find` to build the list of files you want to restyle yourself:

```console
find -type f \
  -any -other -options -you -need \
  -exec restyle-path {} \+
```

**Comment by terafin** [comment]
Thanks! I'm sure blocking symlinks altogether would break something so that makes sense... 

FWIW, I think it would be good to apply excludes here, seems to follow the .gitignore model where you can just have a large hammer to exclude things. Would it be more inline with separation to have a .restyler_ignore.yaml then that both of them look at? I'm happy to take a stab at some changes if you have a direction you'd like to go.

**Comment by pbrisbin** [comment]
OK, I think that's fair. We already have the separation between global [`exclude`](https://github.com/restyled-io/restyler/blob/master/config/default.yaml#L21)s and the individual `restyler[].include` patterns; and I was thinking about this for the individual Restylers' option.

>  I'm happy to take a stab at some changes if you have a direction you'd like to go.

I think we can move the "expand directories" logic inward, so that it happens after the global `exclude` is consulted (but still before the individual Restyler's `include` is used).

That would happen here:

```hs
runRestylersWith
    :: (HasSystem env, HasLogFunc env)
    => (Restyler -> [FilePath] -> RIO env b)
    -> Config
    -> [FilePath]
    -> RIO env [b]
runRestylersWith run Config {..} allPaths = do
    paths <- filterM doesFileExist $ filter included allPaths

    logDebug $ "Restylers: " <> displayShow (map rName restylers)
    logDebug $ "Paths: " <> displayShow paths

    for restylers $ \r -> run r =<< filterRestylePaths r paths
  where
    included path = none (`match` path) cExclude
    restylers = filter rEnabled cRestylers
```

Instead of

```hs
paths <- filterM doesFileExist $ filter included allPaths
```

You would want to implement 

```hs
paths <- expandDirectories $ filter included allPaths
```

Which handles both expanding any directory arguments, and filtering to only things that exist. At that point you can update `restyle-path` to _not_ do that, and all should be well.

The only perhaps) tricky part, is this will require adding `doesDirectoryExist` and `listDirectory` members to the `HasSystem` class. This'll trigger a bunch of book-keeping updates, but it should be easy to follow the existing members' as reference.

**Comment by terafin** [comment]
Thanks, will try to take a peek at it this week!

**Comment by pbrisbin** [comment]
HI there @terafin, no pressure whatsoever but I'm just wondering: do you still plan to tackle this, or if I should consider it free to look at myself?

**Comment by terafin** [comment]
My apologies, work has gotten a little crazy. Thankfully a fancy find script worked around this for now, and I'm not likely to get to this soon :(
